server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Compresión Gzip para mayor velocidad
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # El Service Worker sw.js no debe almacenarse en caché estricta para actualizar la PWA automáticamente
    location = /sw.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }

    # Caché eficiente para recursos estáticos
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|csv)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }
}
